CREATE TABLE IF NOT EXISTS PRICES (
  ID int(11),
  BRAND_ID int(11),
  START_DATE TIMESTAMP,
  END_DATE TIMESTAMP,
  PRICE_LIST int(11),
  PRODUCT_ID int(11),
  PRIORITY int(11),
  PRICE DECIMAL,
  CURRENCY varchar(255),
  PRIMARY KEY (ID)
);
